apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w0l71prml-go
  janus-idp.io/tekton: w0l71prml-go
  backstage.io/kubernetes-id: w0l71prml-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w0l71prml-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
